#!/bin/bash -x

  srcSize=$(blockdev --getsize64 /dev/mmcblk0)
  minSize="$((20 * srcSize / 11))"
  #minsize=$(expr "1.9 * $srcsize")
  destSize=$(blockdev --getsize64 /dev/sda)
  if [[ "$destSize" -gt "$minSize" ]]; then
    echo "$minsize"; return 1;
  fi

