# Note RPi3 base (first RPi to have aarch64 available)
# ATTENTION: Zulu Java on raspberrypi3 images fails to run
FROM balenalib/raspberrypi3-debian-node:latest-buster-build


ENV container docker
ENV INITSYSTEM on
ENV APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=DontWarn

# Currently this config is used for BATS tests.
# bats tests on a minimal install will require additional packages to run properly:
# - lsb-release (influx, homegear)
# - psmisc, i.e. killall (homegear)
# - unzip (java)
# those packages would normally be included in our standard install
RUN apt-get update -qq \
    && apt-get install --yes -qq --no-install-recommends systemd systemd-sysv git wget python3 python3-pip apt-utils jq virt-what \
       lsb-release unzip apt-transport-https \
    && rm -rf /var/lib/apt/lists/*
RUN git clone https://github.com/bats-core/bats-core.git && \
    cd bats-core && \
    ./install.sh /usr/local

# We never want these to run in a container
# Feel free to edit the list but this is the one we used
RUN systemctl mask \
    dev-hugepages.mount \
    sys-fs-fuse-connections.mount \
    sys-kernel-config.mount \
    display-manager.service \
    getty@.service \
    systemd-logind.service \
    systemd-remount-fs.service \
    getty.target \
    graphical.target

WORKDIR /
COPY docker-tests/entry.sh /usr/bin/entry.sh
COPY docker-tests/resin.service /etc/systemd/system/resin.service

RUN systemctl enable /etc/systemd/system/resin.service

RUN git clone https://github.com/gdraheim/docker-systemctl-replacement
RUN cp docker-systemctl-replacement/files/docker/systemctl3.py /bin/systemctl

ENTRYPOINT ["/usr/bin/entry.sh"]

RUN adduser openhabian --gecos "openHABian,,," --disabled-password
RUN adduser openhab --gecos "openHABian,,," --disabled-password
RUN echo "openhabian:openhabian" | chpasswd
RUN echo "openhab:openhabian" | chpasswd
RUN /bin/echo -n "Running on " && /usr/bin/arch

COPY . /opt/openhabian/
COPY build-image/openhabian.conf /etc/openhabian.conf

WORKDIR /opt/openhabian/
COPY docker-tests/start.sh ./

VOLUME ["/sys/fs/cgroup"]
STOPSIGNAL 37

CMD ["bash", "start.sh"]
