# Note RPi3 base (first RPi to have aarch64 available) WITH 64bit OS
FROM balenalib/raspberrypi3-64-debian:bullseye-build

ENV DOCKER=1

RUN git clone https://github.com/gdraheim/docker-systemctl-replacement && \
    cp docker-systemctl-replacement/files/docker/systemctl3.py /usr/bin/systemctl

# Setup openHABian environment
COPY . /opt/openhabian/
WORKDIR /opt/openhabian/
RUN install -m 755 ./tests/runlevel /sbin/runlevel

ENTRYPOINT ["/usr/bin/systemctl"]
