FROM balenalib/amd64-debian:bullseye-build

ENV APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=DontWarn
ENV DOCKER=1
ENV UDEV=on
ENV INITSYSTEM=on

# Install systemd
RUN apt-get update -qq && \
    apt-get install --yes -qq --no-install-recommends systemd systemd-sysv && \
    rm -rf /var/lib/apt/lists/*

RUN systemctl mask \
    dev-hugepages.mount \
    sys-fs-fuse-connections.mount \
    sys-kernel-config.mount \
    display-manager.service \
    getty@.service \
    systemd-logind.service \
    systemd-remount-fs.service \
    getty.target \
    graphical.target \
    kmod-static-nodes.service

ENTRYPOINT ["./tests/entry.sh"]

RUN git clone https://github.com/gdraheim/docker-systemctl-replacement && \
    cp docker-systemctl-replacement/files/docker/systemctl3.py /bin/systemctl

# Setup openHABian environment
COPY . /opt/openhabian/
WORKDIR /opt/openhabian/
RUN install -m 755 ./tests/runlevel /sbin/runlevel

CMD ["bash", "./tests/start.sh"]
