# Note RPi4 base WITH 64bit OS
FROM balenalib/raspberrypi4-64-debian:bullseye-build

# Install systemd
# Additionally, BATS tests on a minimal install will require additional packages
# to run properly:
# - lsb-release (influx, homegear)
# - apt-transport-https (homegear, AdoptOpenJDK)
# - unzip (java)
# those packages would normally be included in our standard install
RUN apt-get update -qq && \
    apt-get install --yes -qq --no-install-recommends systemd systemd-sysv \
        git wget python3 python3-pip apt-utils jq lsb-release unzip \
        apt-transport-https gnupg acl && \
    rm -rf /var/lib/apt/lists/*

ENV APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=DontWarn
ENV DOCKER=1
ENV UDEV=on
ENV INITSYSTEM=on

RUN systemctl mask \
    dev-hugepages.mount \
    sys-fs-fuse-connections.mount \
    sys-kernel-config.mount \
    display-manager.service \
    getty@.service \
    systemd-logind.service \
    systemd-remount-fs.service \
    getty.target \
    graphical.target \
    kmod-static-nodes.service

ENTRYPOINT ["./tests/entry.sh"]

RUN git clone https://github.com/gdraheim/docker-systemctl-replacement && \
    cp docker-systemctl-replacement/files/docker/systemctl3.py /bin/systemctl

# Setup openHABian environment
RUN git clone https://github.com/bats-core/bats-core.git && \
    cd bats-core && \
    ./install.sh /usr/local

RUN adduser openhabian --gecos "openHABian,,," --disabled-password && \
    adduser openhab --gecos "openHABian,,," --disabled-password && \
    echo "openhabian:openhabian" | chpasswd && \
    echo "openhab:openhabian" | chpasswd

COPY . /opt/openhabian/
WORKDIR /opt/openhabian/
RUN install -m 755 ./tests/runlevel /sbin/runlevel

CMD ["bash", "./tests/start.sh"]
