FROM balenalib/generic-debian:bullseye-build

ENV container docker
ENV APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=DontWarn
ENV DOCKER=1
ENV UDEV=1
ENV INITSYSTEM=1

# Install systemd
# Additionally, BATS tests on a minimal install will require additional packages
# to run properly:
# - lsb-release (influx, homegear)
# - apt-transport-https (homegear, AdoptOpenJDK)
# - unzip (java)
# those packages would normally be included in our standard install
RUN apt-get update -qq && \
    apt-get install --yes -qq --no-install-recommends systemd systemd-sysv \
        git wget python3 python3-pip apt-utils jq lsb-release unzip \
        apt-transport-https gnupg acl && \
    rm -rf /var/lib/apt/lists/*

RUN systemctl mask \
    dev-hugepages.mount \
    sys-fs-fuse-connections.mount \
    sys-kernel-config.mount \
    display-manager.service \
    getty@.service \
    systemd-logind.service \
    systemd-remount-fs.service \
    getty.target \
    graphical.target \
    kmod-static-nodes.service

COPY ./tests/balena.service /etc/systemd/system/balena.service
RUN systemctl enable /etc/systemd/system/balena.service

STOPSIGNAL 37
ENTRYPOINT ["./tests/entry.sh"]

# Setup openHABian environment
RUN git clone https://github.com/bats-core/bats-core.git && \
    cd bats-core && \
    ./install.sh /usr/local

RUN adduser openhabian --gecos "openHABian,,," --disabled-password && \
    adduser openhab --gecos "openHABian,,," --disabled-password && \
    echo "openhabian:openhabian" | chpasswd && \
    echo "openhab:openhabian" | chpasswd

COPY . /opt/openhabian/
WORKDIR /opt/openhabian/
RUN install -m 755 ./tests/runlevel /sbin/runlevel
