#!/usr/bin/env bash
set -x
BASEDIR=/opt/openhabian
CONFIGFILE=/etc/openhabian.conf

source $CONFIGFILE

source ${BASEDIR}/functions/helpers.bash
source ${BASEDIR}/functions/storm.house.bash

# Script wird als setup_xx_config aufgerufen mit xx=pv or xx=wb
$(basename $0) "$@"

