#!/bin/bash -x


if [[ $# -ne 2 ]]; then echo "wrong usage !"; exit 1; fi

dir=$2

if [[ "$1" = "recover" ]]; then
	rsync -avrh ${dir}/ /
else
	if [[ -z /etc/ztab ]] || [[ "$1" != "sync" ]]; then echo "FAILED"; exit 1; fi
	while read -r line; do
		case "$line" in
			"#"*)
				# Skip comment line
				continue
				;;
			"")
				# Skip empty line
				continue
				;;
			*)
				set -- $line
				if [[ "$1" = "dir" ]]; then
					rsync -avRh "$5" "${dir}"
				fi
				;;
		esac
	done < /etc/ztab
fi
